### ISSUE TITLE
OAuth2 Protocol Exception: Unexpected status code from token endpoint 

### ISSUE THREAD

**Issue by anilmuppalla** [coursera/courseraoauth2client#4]
I tried the suggestion [here](https://github.com/coursera/courseraprogramming/issues/67) and I am posting the result here as suggested : @zhaojunz 

courseraoauth2client --verbose config authorize --app manage_research_exports 
DEBUG:root:About to read from local file cache file /home/mak/.coursera/manage_research_exports_oauth2_cache.pickle
DEBUG:root:Loaded from file system: {'token': u'CiAAeVJQPzCvREl40e5lhkLtES_wBtFH4R3icFhsKjEo-xIlCMiCBBiBgICAICCBjpLT-yoqELAxwvDX6fm9VzG82cfFmuN4AA', 'expires': 1476302732.911909, 'refresh': u'VQ--yO06FRdjgqK-NJYSlvM6qTuQo1GkAp1zZTkgVBQ'}
DEBUG:root:Attempting to use a refresh token.
DEBUG:root:Posting form data {'client_secret': '', 'grant_type': 'refresh_token', 'client_id': 'sDHC8Nfp-b1XMbzZx8Wa4w', 'refresh_token': u'VQ--yO06FRdjgqK-NJYSlvM6qTuQo1GkAp1zZTkgVBQ'} to token endpoint https://accounts.coursera.org/oauth2/v1/token
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): accounts.coursera.org
DEBUG:requests.packages.urllib3.connectionpool:"POST /oauth2/v1/token HTTP/1.1" 400 None
DEBUG:root:Response from token endpoint: (400) {"msg":"Invalid Code"}
ERROR:root:Encountered unexpected status code: 400 <Response [400]> {"msg":"Invalid Code"}
ERROR:root:Encountered an exception during refresh token flow.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 428, in _exchange_refresh_tokens
    tokens = self._request_tokens_from_token_endpoint(refresh_form)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 325, in _request_tokens_from_token_endpoint
    raise OAuth2Exception('Unexpected status code from token endpoint')
OAuth2Exception: OAuth2 Protocol Exception: Unexpected status code from token endpoint
INFO:root:Attempting to retrieve new tokens from the endpoint. You will be prompted to authorize yourapp in your web browser.
INFO:root:About to request new OAuth2 tokens from Coursera.
DEBUG:root:Constructed authoriation request at: https://accounts.coursera.org/oauth2/v1/auth?access_type=offline&state=ebb9097e0a93490e84c2f906887a9e33&redirect_uri=http%3A%2F%2Flocalhost%3A9876%2Fcallback&response_type=code&client_id=sDHC8Nfp-b1XMbzZx8Wa4w&scope=view_profile
Please visit the following URL to authorize this app:
    https://accounts.coursera.org/oauth2/v1/auth?access_type=offline&state=ebb9097e0a93490e84c2f906887a9e33&redirect_uri=http%3A%2F%2Flocalhost%3A9876%2Fcallback&response_type=code&client_id=sDHC8Nfp-b1XMbzZx8Wa4w&scope=view_profile

127.0.0.1 - - [18/Oct/2016 11:26:46] "GET /callback?state=ebb9097e0a93490e84c2f906887a9e33&code=jzMkyCIBrzFMqWiJWTXD8pe8MIDsQ9Es-9MzsjtGcWo HTTP/1.1" 200 -
DEBUG:root:Posting form data {'client_secret': '', 'code': 'jzMkyCIBrzFMqWiJWTXD8pe8MIDsQ9Es-9MzsjtGcWo', 'grant_type': 'authorization_code', 'client_id': 'sDHC8Nfp-b1XMbzZx8Wa4w', 'redirect_uri': 'http://localhost:9876/callback'} to token endpoint https://accounts.coursera.org/oauth2/v1/token
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): accounts.coursera.org
DEBUG:requests.packages.urllib3.connectionpool:"POST /oauth2/v1/token HTTP/1.1" 400 None
DEBUG:root:Response from token endpoint: (400) {"msg":"Invalid Code"}
ERROR:root:Encountered unexpected status code: 400 <Response [400]> {"msg":"Invalid Code"}
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/main.py", line 64, in main
    return args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/commands/config.py", line 37, in authorize
    oauth2_instance.build_authorizer()
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 452, in build_authorizer
    new_tokens = self._authorize_new_tokens()
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 415, in _authorize_new_tokens
    return self._request_tokens_from_token_endpoint(form_data)
  File "/usr/local/lib/python2.7/dist-packages/courseraoauth2client/oauth2.py", line 325, in _request_tokens_from_token_endpoint
    raise OAuth2Exception('Unexpected status code from token endpoint')
OAuth2Exception: OAuth2 Protocol Exception: Unexpected status code from token endpoint

**Comment by zhaojunz** [comment]
@anilmuppalla, thanks. have you tried to delete the pickle file and rerun the command yet? 

`rm /home/mak/.coursera/manage_research_exports_oauth2_cache.pickle`

**Comment by anilmuppalla** [comment]
Yes this worked!

**Comment by zhaojunz** [comment]
Great! As a side note, we probably have some bug around refreshing token. I will let @cliu587 to take a look when he is back.

**Comment by anilmuppalla** [comment]
Awesome! Keep the great work guys!

**Comment by cliu587** [comment]
@zhaojunz thanks for looking into it. Do you mind opening an issue regarding the token refresh bug to explain it in more details?
